name: Unit Tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Composer dependencies
        run: composer install
      - name: PHPUnit Tests
        run: vendor/bin/phpunit
